lamassuiot/lamassuiot

pkg/v3/services/dmsmanager.go
Fix Sonar Issue - https://sonarcloud.io/project/issues?open=AYxsqcZmWf5D68QQJEXi&id=lamassuiot_lamassuiot
=> Fix sonar - Remove this conditional structure or edit its code blocks so that they're not all the same.

ci/aws-connector.dockerfile, ci/ca.dockerfile
This PR upgrades ubuntu image for ca dockerfile and includes some clean steps at ca.dockerfile and aws-connecto.dockerfile
=> Fix sonar - Add cleanning steps to dockerfiles

ci/ca.dockerfile
This PR avoid extra package installation and clean the compilation dependencies
=> fix(sonar) - Reduce ca image surface

.github/workflows/ci-test.yaml
Initial workflow registration on main for testing
=> ci: Add workflow for testing

cmd/monolithic/development/main.go, pkg/assemblers/ca_test.go, pkg/cryptoengines/vaultkv2.go, pkg/services/devicemanager.go, pkg/services/dmsmanager.go, pkg/services/iot/aws.go, pkg/storage/postgres/devicemanager.go, pkg/test/subsystems/storage/postgres/postgres.go
This PR fixes the minor issues found by the go report service at https://goreportcard.com/report/github.com/lamassuiot/lamassuiot/v2
- applies goftm with simplify option
- fixes some typos in the code
- Add missing device Id to the log
=> Fix typo and apply gofmt simplify

.github/workflows/ci-test.yaml, pkg/assemblers/ca_test.go, pkg/assemblers/va_test.go
This PR adds a new workflow that runs the tests when a PR is opened or updated.
It also refines the ca_test.go test suite:
- Manages ignored errors
- Reduce log level
- Skips unreliable tests that have tu be fixed
=> CI - Launch Tests on PR create or update

pkg/controllers/utils.go, pkg/services/dmsmanager.go
- Fixes possible SQL injection if field was not in the filtrable fields dictionary
- Renaming some variables + adding logs while checking certificate expiration
=> SQL Injection 

.github/workflows/gosec.yml
This PR adds gosec analysis tool to the CI
=> Add Gosec to CI

pkg/helpers/cryptosubject_test.go, pkg/helpers/cryptoutils_test.go, pkg/helpers/expiration_test.go, pkg/helpers/keystrength_test.go, pkg/helpers/maps_test.go, pkg/helpers/metadata_test.go, pkg/helpers/serialnumber.go, pkg/helpers/serialnumber_test.go, pkg/helpers/x509fingerprint_test.go
This PR adds unit testing for helpers package. This PR contains only new test without changing the existing logic.
=> Add unit testing for helpers

pkg/assemblers/ca_test.go, pkg/assemblers/device-manager_test.go, pkg/assemblers/service-assembler_test.go, pkg/assemblers/va_test.go, pkg/services/ca.go
=> Adding existing logic to check for CA expiration deltas and fixed test typo

pkg/assemblers/service-assembler_test.go, pkg/middlewares/eventpub/ca.go, pkg/services/ca.go
Restore the cron scheduler stop logic during test suite shutdown
=> Fix - Restore cron scheduller stop during test suite shutdown

pkg/helpers/cryptoutils.go, pkg/helpers/cryptoutils_test.go, pkg/models/iot_aws.go, pkg/services/iot/aws.go, pkg/test/e2e/usecase-1.go, pkg/x509engines/x509engine_sign_test.go, pkg/x509engines/x509engine_test.go
=> Adding flexibility for creating SelfSigned CAs + Adding ARN to cert metadata

cmd/monolithic/development/main.go, go.mod, go.sum, pkg/controllers/ca.go, pkg/controllers/va.go, pkg/routes/ca.go, pkg/routes/dmsmanager.go, pkg/services/ca.go, pkg/services/crl.go, pkg/services/ocsp.go, pkg/storage/postgres/utils.go, pkg/test/e2e/usecase-1.go, pkg/test/subsystems/cryptoengines/keyvaultkv2/vaultkv2.go
This PR fixes various linttr issues along the code:
- Simplify type casting
- Remove unused vars
- Remove not required error checkings
- Remove nor required returns
It also removes the unused dependency over swagger generator.
=> Various linter warnings review

cmd/alerts/main.go, cmd/aws/main.go, cmd/ca/main.go, cmd/device-manager/main.go, cmd/dms-manager/main.go, cmd/va/main.go, pkg/assemblers/aws-iot.go, pkg/config/base.go, pkg/config/base_test.go, pkg/config/iot_aws.go
I think queue name shouldn't be hardcoded
=> Fixes hardcoded queue name

codecov.yml
=> chore: customize codecov integration

pkg/assemblers/dms-manager_test.go
The PR only adds tests for CACerts in enroll
=> EST CACerts tests

pkg/eventbus/pubsub_test.go
This PR changes eventbus tests to launch a single container of rabbit and localstack. 
It also add a cleanup action to stop the containers after tests.
No
- [ X] DOES NOT require updating the helm chart
=> test: Refactor to start event buses once during tests

pkg/controllers/est.go
This PR ensures `content-length` header is added in EST endpoints
=> Adding content-length to EST endpoints

cmd/monolithic/development/main.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Monolithic Fix: renable pkcs11 cryptoengine if configured

pkg/storage/postgres/utils.go
Reverts lamassuiot/lamassuiot#150
=> Revert "Bugfix: Add  filters in bookmark when requestd with bookmark already containing filters"

pkg/services/devicemanager.go
Currently, when a device was decommissioned, during the UpdateIdentitySlot, the function would revoke immediately the device's certificate, causing the DeviceManager to once again call UpdateIdentitySlot causing a race condition due to the device not being fully Decommissioned (the first call to the function was not executed completly causing the device not being marked as Decommisioned before the second invocation) 
=> [FIX] Device Manager: handle decomission correctly

pkg/assemblers/dms-manager_test.go, pkg/clients/utils.go, pkg/controllers/est.go, pkg/models/dms.go, pkg/models/est.go, pkg/routes/est.go, pkg/services/dmsmanager.go, pkg/test/monolithic/lamassu_pki.go
EST ServerKeyGen endpoint is now available. Each DMS can disable the endpoint and decide which algorithm and key size is used to generate the private key
=> Feature: EST ServerKeyGen

.github/workflows/ci-test.yaml, codecov.yml
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> chore: configure codecov flags for monorepo

connectors/awsiot/pkg/service.go
This pull request introduces error handling improvements in the `RegisterCA` method of the `AWSCloudConnectorServiceBackend` class in the `connectors/awsiot/pkg/service.go` file. The changes ensure that errors encountered during the CA registration process are properly logged and updated in the metadata.
Error handling improvements:
* Added a deferred function to log errors and update CA metadata if an error occurs during the `RegisterCA` method execution. This includes setting the registration status to `IoTAWSCAMetadataRegistrationFailed` and recording the error message in the metadata.
=> feat: aws-connector - report CA registration error in metadata

backend/go.mod, backend/go.sum, backend/pkg/assemblers/alerts_test.go, backend/pkg/services/alerts/event_filters/eventfilters.go, backend/pkg/services/alerts/event_filters/javascript_registrar.go, backend/pkg/services/alerts/event_filters/javascriptfilter.go, backend/pkg/services/alerts/event_filters/javascriptfilter_test.go, core/pkg/models/alerts.go, go.work.sum
This pull request introduces a new feature to support JavaScript-based event filtering in the alerts service. The most important changes include adding a new condition type for JavaScript, implementing the JavaScript filter, and creating tests for this new functionality.
* [`core/pkg/models/alerts.go`](diffhunk://#diff-cbcd37043f92ff38fd1cbcb8b73f372842226d1cf6f3f96410009686f18aee1dR28): Added a new condition type `JAVASCRIPT` to support JavaScript-based event filtering.
* [`backend/pkg/services/alerts/event_filters/javascriptfilter.go`](diffhunk://#diff-04b50cd293c8cb61825c648232d94585f1a4a921503c0d8d11375ff23db25048R1-R54): Implemented the JavaScript filter functionality using the `otto` JavaScript interpreter. This includes registering the filter and defining the filter logic.
* …
=> feat: add javascript filters support to subscription conditions

engines/storage/postgres/utils.go
This pull request includes changes to improve the handling of query results in the `postgresDBQuerier` methods within the `engines/storage/postgres/utils.go` file. The main improvements involve correctly managing the query limits and handling the existence check more efficiently.
Improvements to query result handling:
* `func (db *postgresDBQuerier[E]) SelectAll(ctx context.Context, queryParams *reso)`: Modified to add an extra record to the limit to check for more results, and adjusted the logic to handle the additional record appropriately.
* `func (db *postgresDBQuerier[E]) SelectExists(ctx context.Context, queryID string)`: Simplified the existence check by using `Limit(1)` and improving error handling.
=> fix: Improved gorm queries to reduce it and avoid recordNotFound errors

backend/pkg/services/devicemanager.go
This PR fixes the following issue: When attempting to decommission a device that does not have an identity, the service experiences a panic due to a nil pointer dereference. This error should be properly handled instead of causing the service to crash.
To fix the issue a null check has been added before accessing the device identity in the `UpdateDeviceStatus` method of `DeviceManagerServiceBackend`.
Closes #249 
The `ViewDevice.tsx` file has been modified to check whether the device details must be shown. When the device has no identity the details are hidden.
=> fix: DMS Manager: add a null check when decommissioning a device wihtout identity

backend/pkg/middlewares/eventpub/devices_publisher_test.go
This pull request adds new test cases to the **event publisher middleware** tests, specifically covering the `DeleteDevice` operation. The tests ensure that:
- When `DeleteDevice` completes without errors, the appropriate event is fired.
- When `DeleteDevice` returns an error, no event is published.
=> test: middleware: add DeleteDevice case to event publisher
