ci/alerts.dockerfile, ci/aws-connector.dockerfile, ci/ca.dockerfile, ci/devmanager.dockerfile, ci/dmsmanager.dockerfile, ci/va.dockerfile
This PR addresses  the Security Hotspots reported by SonarQube
- Better control on the resources copied at the first stage
- Better control the packages installed ignoring apt-get recommended
- Reduce exposure by running process using a non-root user
=> fix(sonar): Reduce docker images surface

pkg/models/tiemduration.go
I've seen that some durations that include nanoseconds trigger 
```
runtime error: index out of range [-1]
/usr/local/go/src/runtime/panic.go:114 (0x439f9b)
/app/pkg/v3/models/tiemduration.go:366 (0x9d2b74)
/app/pkg/v3/models/tiemduration.go:339 (0x9d2b65)
/app/pkg/v3/models/tiemduration.go:12 (0xdc076f)
```
I could reproduce it using the following main program: 
```go
now := time.Date(2023, time.December, 29, 15, 18, 2, 1, time.Local)
currentDeviceCert := time.Date(2023, time.December, 29, 15, 20, 0, 2, time.Local)
dms, _ := models.ParseDuration("50y")
comparisonTimeThreshold := currentDeviceCert.Add(-time.Duration(dms))
logrus.Infof(
"current device certificate expires at %s (%s duration). DMS allows reenrolling %s. Reenroll window opens %s. (delta=%s)", …
```
=> fix durationToString while using nanoseconds

.github/workflows/ci-test.yaml, pkg/helpers/slices/compare.go, pkg/helpers/slices/compare_test.go
This PR fixes the unordered slices comparison
There was bug in the comparison logic. We were comparing the first slice with itself and not with the second slice.
A test has been added for this logic
=> Fix unordered slices comparison

pkg/storage/postgres/castore.go, pkg/storage/postgres/certstore.go, pkg/storage/postgres/devicemanager.go, pkg/storage/postgres/dmsmanager.go, pkg/storage/postgres/eventstore.go, pkg/storage/postgres/subscriptionstore.go, pkg/storage/postgres/utils.go
All SQL/postgres high level ops can be made with one Gorm low level op. This PR contains such modification. It also removes an spurios/unused call to SelectExists during Update.
=> tweaked postgres ops to improve performance

pkg/controllers/utils.go
This PR solves adding uncontrolled fields in queries. It can be though that this allows a "soft/minor" SQL injection. All filterMaps needs to be checked to ensure that no internal columns can be used externally.
=> Prevent "soft" SQL injections

pkg/assemblers/ca_test.go, pkg/assemblers/device-manager_test.go, pkg/assemblers/service-assembler_test.go, pkg/assemblers/va_test.go, pkg/test/subsystems/storage/postgres/postgres.go, pkg/test/subsystems/storage/postgres/test_suite.go
This PRs adds new tests for the device manager service. It includes basic integration tests supported on a conainerized Postgres as persistence support. 
It launch Postgres, initialize the databases and launch a CA service required by the deivice manager. 
The tests perform a basic creation, read and update test and check the pagination support. 
It has been required to modify the posgres_test support in order to consider multiple DB connection, one for earch service ( CA and Device Manager).
=> Integration tests for Device Manager service

ci/alerts.dockerfile, pkg/controllers/est.go
I've experienced Issues while sending a webhook to sites that have public certificates. This should address that
=> Adding basic CAs in docker image + serializing error correctly in EST

.github/workflows/main.yaml
A unshallowed fetch is required to merge main into v<MajorVersion> branch is required
=> (ci) - Fix merge main into major release branch

.github/workflows/ci-test.yaml, .github/workflows/gosec.yml, .github/workflows/main-release.yaml
This PR upgrades workflow actions to the node 20 version. Actions supported on node 16 will be deprecated on December 2024
=> chore(ci): Upgrade actions to node 20

pkg/storage/postgres/eventstore.go
This PR fixes the storage of the first event of each type seen by the alerts service. 
Previously only an update was tried but when the events table is not previously populated with an event of each type an insert is required.
=> Fix first event storage at eventstore.

pkg/config/aws_sdk.go, pkg/config/ca.go, pkg/config/enums.go
I think that rather than using always static AWS credentials to authenticate, using short-term credentials could be a more robust and secure solution.
I have included the next options to authenticate with AWS:
- Default: This option follows the default credential chain specified by AWS in their SDK: [https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/#specifying-credentials](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/#specifying-credentials). This option may be interesting when running Lamassu in an EC2 machine with an instance profile configured or a Lambda function with a role.
- AssumeRole: This option allows assuming a role to perform the AWS actions, instead of using the static credentials.
- Static: This is "default" option nowadays.
@haritzsaiz Maybe these …
=> Extends AWS Authentication methods

pkg/helpers/cryptoutils.go, pkg/helpers/cryptoutils_test.go
This PR proposes a minor code cleanup at:
pkg/helpers/cryptoutils.go 
- Removed `err != nill` check as it should be allways nill at thet point.
- 
pkg/helpers/cryptoutils_test.go   
- Optimize shwitch to avoid type casting
=> Minor code cleanup

pkg/assemblers/alerts.go, pkg/assemblers/ca.go, pkg/assemblers/device-manager.go, pkg/assemblers/dms-manager.go, pkg/storage/builder/builder.go, pkg/storage/couchdb/engine.go, pkg/storage/engine.go, pkg/storage/postgres/engine.go
This pull request (PR) presents a significant refactor of our current storage engine implementation, aiming to improve the overall structure and functionality of our system. The primary focus of this refactor is to decouple the storage engines from the assemblers, a change that will bring about a more modular and flexible architecture.
In the existing setup, the assembler is responsible for selecting the Storage Engine implementation to be used. This tight coupling between the assembler and the storage engine can lead to limitations in scalability and maintainability, as changes in one component often require corresponding changes in the other.
With the proposed refactor, the selection of the Storage Engine implementation is no longer a responsibility of the assembler. Instead, this task …
=> Storage engine refactor - Decouple assemblers from storage engines

pkg/config/aws_sdk.go, pkg/config/aws_sdk_test.go, pkg/storage/builder/builder_test.go, pkg/test/subsystems/storage/couchdb/couchdb.go
This PR adds a basic test of the new storage engine builder. It also includes new testing support for CouchDB container launch.
=> Add test to storage engine builder

pkg/assemblers/ca.go, pkg/assemblers/device-manager.go, pkg/assemblers/dms-manager.go, pkg/jobs/crypto-monitor-job_test.go, pkg/middlewares/eventpub/ca.go, pkg/middlewares/eventpub/ca_publisher_test.go, pkg/middlewares/eventpub/devices.go, pkg/middlewares/eventpub/devices_publisher_test.go, pkg/middlewares/eventpub/dms.go, pkg/middlewares/eventpub/dms_publisher_test.go, pkg/middlewares/eventpub/utils.go, pkg/models/events.go, pkg/services/mock/caservice_mock.go, pkg/services/mock/devicemanager_mock.go, pkg/services/mock/dms_mock.go
This pull request introduces the following changes to improve the testability and maintainability of our codebase:
1. **Mock-Based Tests for Event Publishers Middleware**: To ensure the reliability and correctness of our event publishing functionality, I've added a suite of mock-based tests for the event publishers middleware. These tests the event firing when no error is produced by the underlying service logic.
2. **Creation of Mocks for Services**: To enable effective unit testing, I've created mocks for our services. These mocks mimic the behavior of the actual services, allowing us to test the interactions between our components in isolation, without relying on external dependencies or affecting other parts of the system.
=> test: add mock based test to event publisher middelwares 

pkg/cryptoengines/pkcs11.go, pkg/cryptoengines/pkcs11w.go, pkg/storage/builder/builder.go, pkg/storage/builder/builder_couchdb_test.go, pkg/storage/builder/builder_experimental_test.go, pkg/storage/builder/builder_test.go, pkg/storage/couchdb/castore.go, pkg/storage/couchdb/certstore.go, pkg/storage/couchdb/devicemanager.go, pkg/storage/couchdb/dmsmanger.go, pkg/storage/couchdb/engine.go, pkg/storage/couchdb/placeholder.go, pkg/storage/couchdb/utils.go, pkg/storage/engine.go, pkg/storage/postgres/engine.go, pkg/test/subsystems/storage/couchdb/couchdb.go
This pull request aims to provide more flexibility and control over the build process of Lamassu by introducing two new build tags: **experimental** and **windows**.
- **Experimental Tag**: This tag is designed to control the inclusion of experimental features in the build. By default, these features are not included in the build. However, if you want to include them, you can do so by specifying the experimental tag in the build command. Currently, the CouchDB storage engine is considered an experimental feature and will be excluded from the build if the experimental tag is not present.
`go build -tag experimental` enables experimental features
**- Windows Tag**: This tag is intended to handle platform-specific compatibility issues. When the windows tag is present in the build command, …
=> Use golang build tags to customize build 

pkg/storage/builder/couchdb_register.go, pkg/storage/builder/postgres_register.go, pkg/storage/couchdb/engine.go, pkg/storage/postgres/engine.go
As postgres was not directly imported by any other element in the code base it was not registered.
=> hotfix: no storage engine was registered as main is only executed on package load

pkg/cryptoengines/vaultkv2.go
Vault cryptoengine would not work on CA restart if path already existed: 
Vault mount paths have an ending slash. This PR ensures the traling slaish is added while checkig if it existed
=> Fixing vault restart path check

pkg/storage/postgres/utils.go
Currently, if a bookmark contained a filter, it would generate an invalid bookmark such as: off:1;lim:1;sortM:desc;sortB:creation_timestampfilter:aWQ=-3-dGVzdA== 
Instead, the bookmark should be:
off:1;lim:1;sortM:desc;sortB:creation_timestamp;filter:aWQ=-3-dGVzdA== 
Note the missing **;** between sortB and filter key words
=> Bug: Missing bookmark filter separator

.github/workflows/dev-release.yaml, pkg/storage/postgres/utils.go
Currently, if a bookmark contains a filter, it would be not included on the newly generated bookmark, rendering the newly string "usless" .
=> Bugfix: Add  filters in bookmark when requestd with bookmark already containing filters

.github/workflows/dev-release.yaml, pkg/services/handlers/device-handlers.go
Update device status from Revoked to Active when a certificate is reactivated. This can only happen when a certificate was revoked with the "on-hold" status and is then reactivated.
=> Bugfix: Update device status when certifiate is updated to Active from Revoked status

pkg/assemblers/alerts.go
This PR adds the missing SMTP configuration that the Alerts service builder needs on the assembler.
=> fix: Alerts: add missing SMTP config to service builder

pkg/controllers/est.go, pkg/routes/est_test.go, pkg/services/mock/est_mock.go
This PR mainly adds new tests on the EST routes and controller using an EST mock service. It ensures that the EST endpoints respond with the correct headers. 
A minor fix is included in the CACerts endpoint to match to the behaviour of the rest of endpoints. It will now fail if no APS context is provided. 
- [ X] DOES NOT require updating the documentation
No
- [ X] DOES NOT require updating the helm chart 
- [ X] DOES NOT require updating UI with new fuctionalities
No
=> test: EST: add new test to the EST routes and controller

pkg/assemblers/dms-manager_test.go, pkg/models/dms.go, pkg/services/dmsmanager.go
This PR introduces a new feature that allows the enrollment of devices using expired certificates. This behavior can be configured at the DMS level, providing flexibility in device onboarding processes. The change enhances our system's capability to handle various certificate scenarios, potentially improving device management in environments where certificate renewal might be challenging.
The following documentation sections should be updated:
- DMS Configuration
If UI changes are required, indicate which sections …
=> feat: DMS: Allow enrollment with expired certificates

backend/pkg/assemblers/ca_test.go, backend/pkg/x509engines/x509engine.go
This pull request includes several changes to the `backend/pkg/assemblers/ca_test.go` and `backend/pkg/x509engines/x509engine.go` files, focusing on improving the reliability and accuracy of the certificate authority (CA) testing and signature verification processes. The most important changes include removing an unused import, re-enabling a previously skipped test, and updating the signature verification tests to handle different algorithms and message types.
* Removed the unused `base64` import in `backend/pkg/assemblers/ca_test.go`.
* Re-enabled the `TestSignatureVerify` test by removing the `t.Skip` call, allowing it to run during testing.
* Updated the `TestSignatureVerify` test to include new test cases for `RSASSA_PSS_SHA_256` and `RSASSA_PKCS1_V1_5_SHA_384` algorithms, and …
=> Fix tests: Signature Sign & Verify

monolithic/cmd/development/main.go
This pull request includes updates to the `monolithic/cmd/development/main.go` file to rename the `GolangFS` crypto engine option to `Filesystem`. The changes ensure consistency across the codebase by updating references to the renamed option.
Key changes include:
* Renamed `CryptoEngineOption` constant from `GolangFS` to `Filesystem` in the `const` block.
* Updated the default value of the `cryptoengines` flag from `golangfs` to `filesystem`.
* Modified the initialization of the `cryptoengineOptionsMap` to use `Filesystem` instead of `GolangFS`.
* Changed the initialization of the `cryptoEngines` slice to be an empty slice instead of a slice with one element.
* Updated the conditional check and configuration for the `Filesystem` crypto engine, including changing the default engine ID …
=> fix monolithic cryptoengines spawn

.github/workflows/main-release.yaml
This pull request makes changes to the GitHub Actions workflow for the main release process. The primary change is the removal of the step that creates a GitHub release for each module.
Go only requires tagging for each module, not a release per module
=> chore: simplify relese to just one. Remove releases per each module

core/pkg/models/ca.go
This PR fixes an issue introduced at PR #197 where the json encoding tags were not defined.
=> fix: add json serialization tags to CACertificate struct

connectors/awsiot/pkg/service.go
This pull request includes a change to the `RegisterAndAttachThing` function in the `AWSCloudConnectorServiceBackend` class within the `connectors/awsiot/pkg/service.go` file. The change updates how the CA ID is retrieved and logged for a device.
Key change:
* Modified the `RegisterAndAttachThing` function to use `IssuerCAMetadata.ID` instead of `AuthorityKeyId` for retrieving the CA ID and updating the error logging accordingly.
=> fix: AWS Connector: use issuer metadata to refer caid

backend/pkg/controllers/est.go
This pull request includes a minor update to the `backend/pkg/controllers/est.go` file. The change adds a `Content-Length` header to the HTTP response in the `GetCACerts` function to specify the length of the PEM file content.
* [`backend/pkg/controllers/est.go`](diffhunk://#diff-4eeba5bff7bbe5ca14b7f70ae2f60fef8d109c8d20cf684ecb51badcbf42ffb9R70): Added `Content-Length` header to the HTTP response in the `GetCACerts` function.
=> fix: EST: add content length in cacerts download with PEM support

.github/workflows/ci-test.yaml
This pull request includes a small change to the `.github/workflows/ci-test.yaml` file. The change updates the name of the CI workflow from "CI Launch Tests" to "GO Unit Testing".
=> chore: rename ci-test worflow

backend/pkg/assemblers/ca_test.go, backend/pkg/assemblers/dms-manager_test.go, backend/pkg/assemblers/service-assembler_test.go, backend/pkg/x509engines/x509engine.go, backend/pkg/x509engines/x509engine_test.go, core/pkg/models/ca.go, core/pkg/models/x509_keyusage.go, core/pkg/models/x509_keyusage_test.go, engines/storage/postgres/migrations_test/utils.go
This pull request includes multiple changes to improve the handling of key usage and extended key usage in certificate issuance, as well as adding new test cases for these functionalities. The most important changes include modifying the `X509KeyUsage` and `X509ExtKeyUsage` structures and their associated methods, updating the `IssuanceProfile` struct, and adding comprehensive test cases.
* [`core/pkg/models/ca.go`](diffhunk://#diff-d7c84197a128bb02fdb2f86c24923f368dc245f5d1bd13a0ee997930651ee7bbL135-R135): Changed `KeyUsage` from a slice to a single `X509KeyUsage` type in the `IssuanceProfile` struct.
* [`core/pkg/models/x509_keyusage.go`](diffhunk://#diff-04a9c7c83f177ea0630c33deb14692b8fd7b4f1167b8fc3ba0261572d2a9f665L12-R12): Modified the `X509KeyUsage` and `X509ExtKeyUsage` …
=> Fix: CA - fixed x509 key serialization

engines/eventbus/aws/aws-sqs-sns.go, shared/aws/docker-emulator.go
This pull request includes changes to ensure the SNS topic exists before creating the subscription and updates the Docker image version for AWS emulation. The most important changes are:
Improvements to AWS SQS Subscription:
* [`engines/eventbus/aws/aws-sqs-sns.go`](diffhunk://#diff-0574c7c2e9da722b58d5bd2281d129b7bf899f61299bbfde83768ee3ce382584R40-R51): Added code to ensure that the SNS topic exists before creating the subscription by creating a new SNS publisher and calling `CreateTopic`.
Updates to Docker Configuration:
* [`shared/aws/docker-emulator.go`](diffhunk://#diff-0fcd2b3102f3fa87835e22ab437634b90c955eac5562a111aa1e8fcce3d4ffb1L19-R19): Updated the Docker image version for AWS emulation from "latest" to "4.1".
=> fix: aws evenbus - ensure sns topic exists before subscribing to sns

backend/pkg/assemblers/ca.go, backend/pkg/assemblers/service-assembler_test.go, backend/pkg/assemblers/va_test.go, backend/pkg/config/ca.go, backend/pkg/controllers/va.go, backend/pkg/routes/va.go, backend/pkg/services/ca.go, backend/pkg/services/crl.go, backend/pkg/x509engines/x509engine.go, backend/pkg/x509engines/x509engine_test.go, core/pkg/resources/careq.go, core/pkg/services/crl.go, monolithic/cmd/development/main.go, monolithic/pkg/assembler.go, monolithic/pkg/config.go, sdk/utils.go, shared/aws/docker-emulator.go
This pull request focuses on updating the CA service configuration to support multiple VA server domains instead of a single domain. The changes span across multiple files, including configuration, service assembly, and X509 engine handling.
Key changes include:
* Updated `CAConfig` to replace `VAServerDomain` with `VAServerDomains`, changing its type from `string` to `[]string`.
* Modified `AssembleCAService` and `BuildCATestServer` functions to use `VAServerDomains` instead of `VAServerDomain`. [[1]](diffhunk://#diff-b87f82107570fc7f691218a78e530d765a3d9469c0206a3acbf3fd9316ee690dL74-R74) [[2]](diffhunk://#diff-18ebc66899d0b8ab6716293d7873e75f775fddd50b13fcf5c7b6ceb07a1c0046L218-R218)
* Updated `CAServiceBackend` and `CAServiceBuilder` to use `VAServerDomains` instead of …
=> feat: ca - Add multiple URLs to CRL and OCSP fields in certificates as well as accesing over http instead of https

backend/pkg/assemblers/va.go, backend/pkg/jobs/va-crl-job.go, backend/pkg/jobs/va-crl-job_test.go, backend/pkg/services/crl.go
This pull request includes several changes to improve the VA CRL monitoring functionality by introducing a scheduler period and refactoring the CRL job logic. The most important changes include adding a new function to calculate the scheduler period, updating the CRL job to use this period, and enhancing test coverage.
* [`backend/pkg/assemblers/va.go`](diffhunk://#diff-8fe0cfe52a16a3428bd5e2d7acc13d21907c0208a6c3195e4942df5de462af8cL110-R133): Added a new function `getSchedulerPeriod` to parse the scheduler period from a cron expression. Updated the `AssembleVAService` function to use this scheduler period when creating the `VACrlMonitorJob`.
* [`backend/pkg/jobs/va-crl-job.go`](diffhunk://#diff-ca8ef19256eae3de61b69e6d1c1a8fa4e55cfa358847dd6e7c90f738c04c1ec8L11-L74): Refactored the …
=> Job Refactor proposal

backend/pkg/assemblers/ca_test.go, backend/pkg/controllers/ca.go, backend/pkg/helpers/x509utils.go, backend/pkg/services/ca.go, backend/pkg/services/crl.go, core/pkg/engines/storage/ca.go, core/pkg/models/ca.go, core/pkg/services/ca.go, engines/storage/postgres/castore.go, engines/storage/postgres/migrations/ca/20250123125500_ca_aws_metadata.go, engines/storage/postgres/migrations/ca/20250226114600_ca_add_kids.go, engines/storage/postgres/migrations/dmsmanager/20241230124809_serverkeygen_revokereenroll.go, engines/storage/postgres/migrations/gomigrations.go, engines/storage/postgres/migrations_test/ca_test.go, sdk/ca.go
This pull request includes several changes to the `backend/pkg` package to improve the handling and testing of certificate authorities (CAs). The most important changes include adding new test cases for CA import, updating the CA import logic to handle parent-child relationships, and adding utility functions for formatting hex data.
* [`backend/pkg/assemblers/ca_test.go`](diffhunk://#diff-9ea5abd3d84e44a0f09b39eab353b4f3dbb36eb90cfa68c4299f37d17ef828b0R2888-R3189): Added new test cases `OK/ImportingHierarchyBottomUp` and `OK/ImportingHierarchyTopDown` to validate the import of CAs in hierarchical order.
* [`backend/pkg/assemblers/ca_test.go`](diffhunk://#diff-9ea5abd3d84e44a0f09b39eab353b4f3dbb36eb90cfa68c4299f37d17ef828b0L4014-R4318): Fixed a typo in the test case name from …
=> Improved ImportCA to update level based on DSN and KID

monolithic/cmd/development/main.go, monolithic/pkg/assembler.go
This pull request includes significant updates to the `monolithic` project, particularly focusing on enhancing the Docker integration and improving the reverse proxy setup. The most important changes are the addition of Docker-related flags and handlers, and the restructuring of the reverse proxy logic.
* Added new imports for Docker-related packages in `monolithic/cmd/development/main.go` to support the integration of Docker functionalities.
* Introduced a new flag `disableUI` to control whether the UI Docker container should be loaded.
* Implemented logic to run a Docker container for the UI if the `disableUI` flag is not set, including setting environment variables and port bindings.
* Added cleanup logic for the UI Docker container to ensure proper resource management.
* Added new …
=> feat:monolithic:lammassui-ui is launched with monolithic. disable-ui flag added to avoid

monolithic/cmd/development/main.go
This pull request includes a small but important change to the `monolithic/cmd/development/main.go` file. The change modifies the `Enabled` field in the `Monitoring` configuration to correctly reflect the state of the `disableMonitor` flag.
* [`monolithic/cmd/development/main.go`](diffhunk://#diff-2986ca8d4d81d984e49859ed7ae335a6effcb228c4f419dfa2362f7dff0e607dL389-R389): Changed the `Enabled` field in the `Monitoring` job configuration to use the negation of the `disableMonitor` flag.
=> fix: Monolithic: Enable MonitoringJob using negated value of disableMonitor flag

monolithic/cmd/development/main.go, monolithic/pkg/assembler.go, monolithic/pkg/config.go
This pull request includes several changes to the `monolithic` project, primarily focusing on enabling dynamic UI port configuration and improving the handling of the UI container. The most important changes are summarized below:
* [`monolithic/cmd/development/main.go`](diffhunk://#diff-2986ca8d4d81d984e49859ed7ae335a6effcb228c4f419dfa2362f7dff0e607dR12): Added import for `strconv` to convert string to integer for the UI port.
* [`monolithic/cmd/development/main.go`](diffhunk://#diff-2986ca8d4d81d984e49859ed7ae335a6effcb228c4f419dfa2362f7dff0e607dL249-L275): Introduced a new variable `uiPort` to store the dynamically assigned port for the UI container and updated the log message to indicate whether the UI is enabled.
* [`monolithic/cmd/development/main.go`](diffhunk://#diff-2986ca8d4d81d98 …
=> chore: launch monolithic UI in a random docker port

monolithic/cmd/development/main.go
This pull request includes a change to the monitoring job frequency configuration in the `monolithic/cmd/development/main.go` file. The frequency has been updated from a cron expression to a more straightforward interval format.
Configuration update:
* [`monolithic/cmd/development/main.go`](diffhunk://#diff-2986ca8d4d81d984e49859ed7ae335a6effcb228c4f419dfa2362f7dff0e607dL391-R391): Changed the `MonitoringJob` frequency configuration from `"* * * * *"` to `"2m"`.
=> chore: adjust monolithic monitoring job

.github/workflows/ci-test.yaml, backend/pkg/assemblers/alerts_test.go, backend/pkg/services/alerts/event_filters/javascriptfilter.go, backend/pkg/services/alerts/event_filters/javascriptfilter_test.go, backend/pkg/services/alerts/event_filters/jsonpathfilter.go, backend/pkg/services/alerts/event_filters/jsonpathfilter_test.go, backend/pkg/services/alerts/event_filters/jsonschemafilter.go, backend/pkg/services/alerts/event_filters/jsonschemafilter_test.go
This pull request includes changes to enhance the event filtering functionality by ensuring consistent data handling and improving test coverage. The most important changes involve modifications to the `javascriptFilter`, `jsonPathFilter`, and `jsonSchemaFilter` functions, as well as updates to their corresponding tests.
Enhancements to event filtering functions:
* [`backend/pkg/services/alerts/event_filters/javascriptfilter.go`](diffhunk://#diff-04b50cd293c8cb61825c648232d94585f1a4a921503c0d8d11375ff23db25048R26-R32): Modified the `javascriptFilter` function to handle the event data consistently by encoding the event to JSON before unmarshalling it.
* [`backend/pkg/services/alerts/event_filters/jsonpathfilter.go`](diffhunk://#diff-7725de5c3c6e5d663a82a18996e5d9e284773d706d28c732337a99c7fd …
=> feat: enhance event filters to use encoded event data for processing

monolithic/cmd/development/main.go
This pull request includes a change to the `monolithic/cmd/development/main.go` file to update the port used for the `uiPort` variable.
* [`monolithic/cmd/development/main.go`](diffhunk://#diff-2986ca8d4d81d984e49859ed7ae335a6effcb228c4f419dfa2362f7dff0e607dL267-R267): Changed the port from `4566/tcp` to `80/tcp` for the `uiPort` variable in the `main` function.
=> fix: ui port now being served correctly

backend/pkg/assemblers/va.go, monolithic/pkg/assembler.go
This pull request refactors the `AssembleVAService` functionality in `backend/pkg/assemblers/va.go` to improve modularity, enhance readability, and add support for additional configurations like event buses and monitoring jobs. The changes include extracting logic into new helper functions and introducing conditional handling for optional features.
* Moved the `serviceID` variable to a global scope for reuse across multiple functions, reducing redundancy. [[1]](diffhunk://#diff-8fe0cfe52a16a3428bd5e2d7acc13d21907c0208a6c3195e4942df5de462af8cR23-R24) [[2]](diffhunk://#diff-8fe0cfe52a16a3428bd5e2d7acc13d21907c0208a6c3195e4942df5de462af8cL43)
* Extracted the logic for setting up the Publisher Event Bus, Subscriber Event Bus, and CRL Monitoring Job into separate helper functions: …
=> feat: VA: assemble service conditionally based on config

backend/pkg/assemblers/ca.go, backend/pkg/assemblers/service-assembler_test.go, backend/pkg/config/ca.go, backend/pkg/services/ca.go
This pull request refactors the V1 to V2 format keys migration process in the Crypto Engines to perform the action from the assembler `backend/pkg/assemblers/ca.go` and not from the service `backend/pkg/services/ca.go`. In addition, this action is conditioned to a new config attribute in `backend/pkg/config/ca.go` in order to give much more control to PKI administrators in situations where this migration should be done by an ad-hoc process.
- Moved the keys migration process from `backend/pkg/services/ca.go` to `backend/pkg/assemblers/ca.go`. [[1]](https://github.com/lamassuiot/lamassuiot/compare/feat/migrate_keys_optionally?expand=1#diff-1386b19b4548f7f93edc168db32d342723d9df9418234395677633a565bfbce9) [[2]](https://github.com/lamassuiot/lamassuiot/compare/feat/migrate_keys_optionally?exp …
=> feat: CA: refactor crypto engine keys migration

core/pkg/engines/cryptoengines/cryptoengine_testset.go, engines/crypto/aws/awskms.go, engines/crypto/aws/awskms_test.go
This pull request introduces the capability to import RSA and ECDSA private keys into the AWS KMS crypto engine, alongside the necessary utilities for key wrapping and encryption. The changes include new methods for handling key imports, updates to the test suite, and the addition of cryptographic utilities to support these operations.
* Added `ImportRSAPrivateKey` and `ImportECDSAPrivateKey` methods to the `AWSKMSCryptoEngine` to enable importing RSA and ECDSA private keys. These methods create keys in AWS KMS, generate aliases, and securely import private key material using AES and RSA-OAEP encryption. (`engines/crypto/aws/awskms.go`)
* Introduced the `importPrivateKeyDer` method to handle the encryption and import of private key material into AWS KMS, utilizing AES key wrapping and …
=> feat: CA: implement AWS KMS import keys

backend/go.mod, backend/go.sum, backend/pkg/routes/middlewares/identity-extractors/extractors.go, backend/pkg/routes/middlewares/identity-extractors/jwt.go, go.work.sum
This pull request updates the `golang-jwt` library to version 4.5.2 across the codebase to ensure compatibility with the latest features and security fixes. The changes involve updating the dependency in `go.mod`, modifying import paths in relevant files, and updating the checksum in `go.work.sum`.
* Updated `golang-jwt` from version `v3.2.2+incompatible` to `v4.5.2` in `go.mod` to use the latest major version of the library.
* Adjusted import paths in `backend/pkg/routes/middlewares/identity-extractors/extractors.go` and `backend/pkg/routes/middlewares/identity-extractors/jwt.go` to reflect the new `v4` module path. [[1]](diffhunk://#diff-3295ccce120d2c28385a38ba0d7706c95770453058ca5f8f7559c3e43bfe851cL8-R8) [[2]](diffhunk://#diff-9081fecbe359119408889930e3c8c86babdcbef011adadfed37b79d723 …
=> Bump golang-jwt to 4.5.2

engines/crypto/vaultkv2/go.mod, engines/crypto/vaultkv2/go.sum, go.work.sum
This pull request updates dependencies in the `engines/crypto/vaultkv2` module and its associated workspace. The changes include upgrading versions of key libraries to address potential issues or take advantage of new features.
* Updated `github.com/hashicorp/vault/api` from `v1.15.0` to `v1.16.0` in `engines/crypto/vaultkv2/go.mod` to ensure compatibility with the latest Vault API features.
* Updated `github.com/go-jose/go-jose/v4` from `v4.0.1` to `v4.0.5` in `engines/crypto/vaultkv2/go.mod` to include the latest security and functionality improvements.
* Added checksum entries for `github.com/go-jose/go-jose/v4 v4.0.5` in `go.work.sum` to reflect the updated dependency.
* Removed an unnecessary checksum entry for `github.com/hashicorp/vault/api v1.16.0` in `go.work.sum`, as it was …
=> bump: go-jose to 4.0.5

engines/crypto/aws/awskms.go
This pull request fixes listing AWS reserved KMS key aliases.
- `engines/crypto/aws/awskms.go`: Added a condition to filter KMS keys starting with `alias/aws/` aliases.
=> fix: CA: discard aws reserved kms aliases

engines/storage/postgres/castore.go
This pull request fixes the filtering of CAs by Common Name. To be able to filter by CN, **certificates** table has to be queried:
- `engines/storage/postgres/castore.go`: added a JOIN between **ca_certificates** and **certificates** tables in the query of the `SelectAll` method.
Fixes #253
=> fix: CA:  fix filtering CAs by CN

backend/pkg/assemblers/device-manager_test.go, backend/pkg/assemblers/dms-manager_events_test.go, backend/pkg/assemblers/dms-manager_test.go, backend/pkg/services/dmsmanager.go, backend/pkg/test/e2e/usecase-1.go, core/pkg/models/dms.go, engines/storage/postgres/migrations/dmsmanager/20250612100530_est_verify_csr_signature.go, engines/storage/postgres/migrations/gomigrations.go, engines/storage/postgres/migrations_test/dms_test.go
This pull request introduces support for verifying **CSR** (Certificate Signing Request) signatures during device **enrollment/reenrollment** in the **DMS** (Device Management Service) and adds corresponding database migration and tests. This update ensures that the DMS supports CSR signature verification as a configurable option, with robust migration and test coverage.
Closes #248 
- Adds a new migration that introduces the `verify_csr_signature `field to the `enrollment_settings` JSON object in the DMS table.
- The new field defaults to `false` for existing records.
- Adds and updates migration tests to ensure the new `verify_csr_signature` field is correctly added and defaults to `false`.
- Refactors and cleans up migration test code for maintainability.
- Ensures all migrations are …
=> feat: DMS Manager: add option to toggle CSR signature verification during Enrollment/Reenrollment

backend/pkg/controllers/utils.go, core/pkg/resources/query.go, engines/storage/postgres/utils.go
This pull request introduces **case-insensitive** filtering support for queries in the backend. The main goal is to ensure that filter operations on string fields (such as ID, CN or tags) ignore case, providing a more user-friendly and predictable search experience.
This update improves the usability of filtering features by making them case-insensitive, ensuring consistent results for users regardless of input casing.
- Updates query logic to perform case-insensitive comparisons when applying filters to string fields.
- Ensures that filters on IDs, Common Names, tags, and other relevant fields match regardless of letter casing.
Closes #269
=> feat: add case-insensitive filtering support

engines/storage/postgres/utils.go
This pull request updates the `SelectAll` function in `engines/storage/postgres/utils.go` to improve URL encoding and decoding for bookmarks and refines string splitting logic for better performance and clarity.
Changes related to bookmark encoding and decoding:
* Updated bookmark decoding to use `base64.URLEncoding` instead of `base64.StdEncoding` for compatibility with URL-safe encoding.
* Updated bookmark encoding to use `base64.URLEncoding` instead of `base64.StdEncoding` to ensure consistency with the decoding process.
Changes related to string splitting:
* Replaced `strings.Split` with `strings.SplitSeq` for handling bookmark splits, potentially improving performance and readability.
=> fix: update bookmark encoding to use URL-safe base64 encoding

backend/pkg/services/crl.go, backend/pkg/services/handlers/va-handlers.go, core/pkg/engines/eventbus/messaging.go, core/pkg/resources/careq.go, engines/storage/postgres/castore.go, monolithic/cmd/development/main.go, sdk/utils.go
This pull request introduces several changes across multiple files to improve functionality, enhance code readability, and fix issues. The most significant updates include modifications to query parameter handling, adjustments to retry intervals, and updates to filter field mappings.
* [`sdk/utils.go`](diffhunk://#diff-b430959ee0d3e59202d926089f0a27cac7b5a05d15fa6efee7bc1a9deb1e49a1L256-R258): Refactored the `IterGet` function to use `url.Parse` for safer URL handling and introduced the `encodeQueryParams` function to dynamically encode query parameters based on `resources.QueryParameters`. This improves the flexibility and reliability of query construction. [[1]](diffhunk://#diff-b430959ee0d3e59202d926089f0a27cac7b5a05d15fa6efee7bc1a9deb1e49a1L256-R258) …
=> Fix: CRL Initialization on event

backend/pkg/assemblers/service-assembler_test.go, engines/crypto/aws/awskms_test.go, engines/crypto/aws/secretsmanager_test.go, engines/crypto/aws/subsystem/subsystem.go, engines/crypto/pkcs11/docker/emulator.go, engines/crypto/pkcs11/pkcs11_test.go, engines/crypto/pkcs11/subsystem/subsystem.go, engines/crypto/vaultkv2/docker/test_suite.go, engines/crypto/vaultkv2/docker/vaultkv2.go, engines/crypto/vaultkv2/subsystem/subsystem.go, engines/crypto/vaultkv2/vaultkv2_test.go, engines/eventbus/amqp/engine_test.go, engines/eventbus/amqp/subsystem/subsystem.go, engines/eventbus/amqp/test/rabbitmq.go, engines/eventbus/aws/engine_test.go, engines/storage/postgres/migrations_test/utils.go, engines/storage/postgres/subsystem/subsystem.go, engines/storage/postgres/test/postgres.go, engines/storage/postgres/test/postgres_test.go, engines/storage/postgres/test/test_suite.go, monolithic/cmd/development/main.go, shared/aws/docker-emulator.go, shared/subsystems/pkg/test/subsystems/subsystems.go, shared/subsystems/pkg/test/subsystems/subsystems_test.go
This pull request introduces the `exposeAsStandardPort` parameter across various subsystems and test utilities to allow optional exposure of services on standard ports. The changes improve flexibility in configuring Docker-based service emulation for testing. Below are the most important changes grouped by theme:
* Added the `exposeAsStandardPort` parameter to the `Run` methods of subsystems like `RabbitMQSubsystem`, `PostgresSubsystem`, `VaultKV2Subsystem`, and `Pkcs11Subsystem`, enabling optional port exposure. [[1]](diffhunk://#diff-02b3a00efc01b28b91993f07235ebe1beebbffabcefea0cbb69f38e1864e079dL18-R19) [[2]](diffhunk://#diff-240aa9a346ca63947e872862d4a6dc2ce1ecc65aaf986ae0e56770f41711c7f7L23-R24) [[3]](diffhunk://#diff-be191c292745bc2fbadc7c3a2d6157c6c06d1d45d4939b629a68850f05e46830L1 …
=> chore: monolithic: add labels and standard ports in docker containers

backend/pkg/assemblers/dms-manager_test.go, backend/pkg/assemblers/va_test.go, backend/pkg/helpers/serialnumber.go, backend/pkg/helpers/serialnumber_test.go, backend/pkg/services/ca.go, backend/pkg/services/dmsmanager.go, backend/pkg/services/ocsp.go, backend/pkg/x509engines/x509engine.go, connectors/awsiot/pkg/service.go, engines/crypto/software/software.go, engines/storage/postgres/migrations/ca/20250904183000_update_serial_numbers.sql, engines/storage/postgres/migrations_test/ca_test.go
This PR standardizes the handling and storage of certificate **serial numbers** across the backend, connectors, and database migrations. The new format is a plain, **lowercase hexadecimal string without dashes,** ensuring consistency and simplifying queries and integrations.
Closes #288
**Helpers Refactor:**
- Replaced `SerialNumberToString` (which used dashed hex) with `SerialNumberToHexString`, producing lowercase hex strings.
- Updated all usages and tests to expect the new format.
**Backend & Connectors Update:**
- Refactored all backend services, logging, and connector logic to use the normalized serial number format.
- Ensured all certificate-related operations use lowercase hex serial numbers.
**Database Migration:**
- Added a migration to update existing certificate and CA …
=> refactor: CA: homogenize certificate SN format

backend/pkg/assemblers/va_test.go, backend/pkg/services/handlers/va-handlers.go
This pull request adds support for regenerating the Certificate Revocation List (CRL) when a certificate is reactivated from a CertificateHold status, ensuring that the CRL is properly updated both for revocation and reactivation events. The changes include updates to the event handling logic and a new test to verify correct CRL behavior.
**CRL Regeneration Logic Improvements:**
* Updated `updateCertificateStatus` in `va-handlers.go` to regenerate the CRL not only when a certificate is revoked, but also when it is reactivated from CertificateHold status. This ensures that certificates are correctly removed from the CRL upon reactivation.
* Added logging to clarify when CRL regeneration occurs due to either revocation or reactivation from CertificateHold, and when regeneration is skipped …
=> feat: va: add support for CRL certificate reactivation from hold 

backend/pkg/assemblers/alerts.go, backend/pkg/assemblers/device-manager.go, backend/pkg/assemblers/dms-manager_events_test.go, backend/pkg/assemblers/va.go, connectors/awsiot/pkg/assembler.go, core/pkg/engines/eventbus/eventbus_testset.go, core/pkg/engines/eventbus/messaging.go, core/pkg/engines/eventbus/subscriber.go, engines/eventbus/amqp/engine_test.go, engines/eventbus/aws/engine_test.go
This pull request introduces significant improvements to the event bus system, primarily by adding support for poison queue handling and enhancing error handling in event-driven services. The changes ensure that messages which repeatedly fail processing are moved to a dead-letter queue (DLQ) for further inspection, improving system reliability and observability. Additionally, the event bus message handler and its usage across the codebase have been updated to support the new publisher parameter required for poison queue functionality. Comprehensive tests have been added to validate error handling and DLQ behavior.
**Event Bus Poison Queue and Middleware Enhancements:**
* Refactored `NewMessageRouter` in `messaging.go` to accept a poison queue publisher, add poison queue middleware, and …
=> fix: add dlq to event bus after 3 retries

backend/pkg/assemblers/ca_test.go, backend/pkg/services/ca.go, core/pkg/services/ca.go
This pull request updates the CA import logic and its associated validation and tests to better distinguish between importing a CA with or without a private key. The changes clarify when a `ProfileID` is required and update the test cases to reflect the new import scenarios.
**Validation logic improvements:**
* In `backend/pkg/services/ca.go`, added a check to require `ProfileID` when importing a CA with a private key, ensuring proper validation for different import scenarios.
**Test case updates:**
* In `backend/pkg/assemblers/ca_test.go`, renamed and updated the test case to `OK/ImportingCAWithoutKey`, removing the issuance profile creation and `ProfileID` assignment for external CA imports without a private key.
* Renamed the test case to `OK/ImportingCAWithKey` to clarify the scenario …
=> fix: ca: import ca without key when profileid not supplied

backend/pkg/assemblers/dms-manager_events_test.go, backend/pkg/middlewares/eventpub/utils.go, backend/pkg/routes/middlewares/basic-header-extractors/extractors.go, backend/pkg/routes/middlewares/basic-header-extractors/extractors_test.go, connectors/awsiot/pkg/event-handlers.go, connectors/awsiot/pkg/models.go, connectors/awsiot/pkg/service.go
This pull request introduces improvements to the handling of AWS IoT policy updates, source context propagation, and source formatting in the backend. The main changes focus on ensuring that only new or changed AWS IoT policies are registered or updated, refining how source context is set and propagated, and updating the format of the AWS IoT source string.
* Enhanced the logic in `createOrUpdateDMSHandler` to register or update only new or changed AWS IoT policies during automatic registration, reducing unnecessary operations.
* In `EventPublisherWithSourceMiddleware`, added a check to ensure the source context is set only if it's missing, preventing overwriting an existing source.
* Updated the `updateContextWithRequestWithSource` function to set the source context directly from the …
=> fix: all: add correct source in cloud events

engines/storage/postgres/migrations/devicemanager/20250925120000_remove_serial_hyphens.go, engines/storage/postgres/migrations/gomigrations.go, engines/storage/postgres/migrations/helpers/rows_iterator.go, engines/storage/postgres/migrations_test/devicemanager_test.go
This PR addresses inconsistencies in device certificate serial number formatting by implementing a database migration that standardizes all serial numbers to lowercase, hyphen-free format across the device manager's `identity_slot` JSON data.
Device certificate serial numbers were stored in an inconsistent format (with hyphens) within the `identity_slot` JSON column: `02-f4-d5-4b-50-bf-26-ba-75-27-68-20-55-51-a9-25`
**Database Migration**
- **File**: `20250925120000_remove_serial_hyphens.go`
- **Target**: `devices` table's `identity_slot` JSON column
- **Transformations**:
- Remove all hyphens from serial numbers
- Convert all serial numbers to lowercase
- Preserve all other JSON fields unchanged
**Example transformation**
``` go
// Before
{
"versions": {
"0": …
```
=> fix: devicemanager: normalize device certificate serial numbers

engines/storage/postgres/migrations/ca/20250908074250_add_profile_id.go, engines/storage/postgres/migrations_test/ca_test.go
This pull request improves the robustness of the CA certificate migration by ensuring that certificates with a NULL `validity_time` are handled gracefully. It also adds comprehensive test coverage to verify this behavior during migration.
**Migration robustness improvements:**
* Updated the migration code in `add_profile_id.go` to safely handle cases where `validity_time` is NULL, preventing panics by checking for nil values before type assertion.
**Test coverage enhancements:**
* Added a test case in `ca_test.go` that inserts a CA certificate with a NULL `validity_time` and verifies that the migration does not panic and still assigns a `profile_id`. [[1]](diffhunk://#diff-c31198a41b6d18cab90da8de04c6806c3d98c9f234db593d000602b5a18daa6eR331-R339) …
=> fix: ca: add migration for profile_id with null in validity_time column in ca_certificates table

backend/pkg/assemblers/alerts.go, backend/pkg/assemblers/device-manager.go, backend/pkg/assemblers/service-assembler_test.go, backend/pkg/assemblers/va.go, backend/pkg/config/alerts.go, backend/pkg/config/devicemanger.go, backend/pkg/config/va.go, backend/pkg/eventbus/pubsub.go, connectors/awsiot/pkg/assembler.go, connectors/awsiot/pkg/config.go, core/pkg/engines/eventbus/messaging.go, monolithic/cmd/development/main.go, monolithic/pkg/assembler.go, monolithic/pkg/assembler_awsiot.go, monolithic/pkg/config.go
This pull request introduces support for configuring a separate Dead Letter Queue (DLQ) event bus for multiple services. The main changes involve updating configuration structs to include a new `SubscriberDLQEventBus` field and ensuring that DLQ publishers use this new configuration. Additionally, the development environment is updated to properly set up and use the DLQ event bus.
Configuration updates:
* Added a `SubscriberDLQEventBus` field of type `EventBusEngine` to the configuration structs for `AlertsConfig`, `DeviceManagerConfig`, `VAconfig`, `ConnectorServiceConfig`, and `MonolithicConfig`, allowing each service to specify a dedicated DLQ event bus. [[1]](diffhunk://#diff-1cd4d349818e7a0e97edd3d131183461e564e1d92ae904974f40576c9c576f36R9) …
=> fix: fixed support for dedicated DLQ event bus configuration across services

backend/pkg/assemblers/ca_certificates_test.go, backend/pkg/controllers/utils_test.go, core/pkg/resources/fields.go
This pull request adds support for filtering certificates by their Subject Key ID (`subject_key_id`). The changes include updates to the certificate filtering logic, test coverage for this new filter, and validation of query parsing in controllers.
* Added `"subject_key_id"` as a supported filter field in the `CertificateFiltrableFields` map in `core/pkg/resources/fields.go`, enabling API clients to filter certificates by their Subject Key ID.
* Added a new test `TestGetCertificatesFilterBySubjectKeyID` to `backend/pkg/assemblers/ca_certificates_test.go` that creates two certificates with different Subject Key IDs and verifies that filtering by `subject_key_id` returns the correct certificate.
* Imported the `resources` package in `backend/pkg/assemblers/ca_certificates_test.go` to …
=> feat: add support to filter certs by subject_key_id
